GDipSA51_Team5/Controllers/GalleryController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using GDipSA51_Team5.Data;
using GDipSA51_Team5.Models;

namespace GDipSA51_Team5.Controllers
{
    public class GalleryController : Controller
    {
        private readonly Team5_Db db;

        public GalleryController(Team5_Db db)
        {
            this.db = db;
        }

        public IActionResult Index(string searchString)
        {
            string sessionId = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionId;

            Session session = db.Sessions.FirstOrDefault(x => x.Id == sessionId);
            if (session != null)
            {
                ViewData["Username"] = db.Users.FirstOrDefault(x => x.UserId == session.UserId).Username;
            }
            else
            {
                ViewData["Username"] = "Guest";
            }

            ViewData["Products"] = db.Products.Where(s => (s.Name.Contains(searchString) || s.Description.Contains(searchString)) || searchString == null).ToList();

            return View();
        }
    }
}

GDipSA51_Team5/Controllers/IdentityControllers/RegistrateController.cs
using System.Linq;
using GDipSA51_Team5.Models;
using Microsoft.AspNetCore.Mvc;
using GDipSA51_Team5.Data;

namespace GDipSA51_Team5.Controllers
{
    public class RegistrateController : Controller
    {
        private readonly Team5_Db db;

        public RegistrateController(Team5_Db db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Authenticate(string username, string NewPWD, string ConfirmedPWD)
        {
            User user = db.Users.FirstOrDefault(x => x.Username == username);
            if (user == null)
            {
                if (NewPWD == ConfirmedPWD)
                {
                    User users = new User()
                    {
                        Username = username,
                        Password = NewPWD,
                    };
                    db.Add(users);
                    db.SaveChanges();
                    return RedirectToAction("Login", "Login");
                }
                else
                {
                    ViewData["errMsg"] = "Please enter a consistent password";
                    return View("Index");
                }
            }
            else
            {
                ViewData["errMsg"] = "user has existed";
                return View("Index");
            }

           
        }
    }
    
}

GDipSA51_Team5/Views/Registrate/Index.cshtml
@section Scripts
{
    <script src="~/js/Registrate.js"></script> ">
}

<style>
    td {
        padding: 5px;
    }
</style>


<header>
    <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <a class="navbar-brand" asp-controller="Gallery" asp-action="Index">> hq_pkgs</a>
        <div class="navbar-collapse">
            <ul class="navbar-nav flex-grow-1">
                @if (ViewData["sessionId"] == null)
                {
                    <li class="nav-item" style="float:right">
                        <a class="nav-link text-dark" asp-controller="Login" asp-action="Login">Login</a>
                    </li>
                }
            </ul>
        </div>
    </nav>
</header>

<p></p>

<form id="form" action="/Registrate/Authenticate" method="post">
    <table align="center">
        <tr>
            <td>Username:</td>
            <td><input id="username" name="username" class="form-control-from" /></td>
        </tr>
        <tr>
            <td>Password:</td>
            <td><input id="NewPWD" name="NewPWD" type="password" class="form-control-from" /></td>
        </tr>
        <tr>
            <td>Confirm your Password:</td>
            <td><input id="ConfirmedPWD" name="ConfirmedPWD" type="password" class="form-control-from" /></td>
        </tr>
        <tr>
            <td colspan="2" align="right"><input id="submitBtn" type="submit" class="button" /></td>
        </tr>

        <tr>
            <td colspan="2" align="center"><div class="err_msg">@ViewData["errMsg"]</div></td>
        </tr>
    </table>
</form>