GDipSA51_Team5/Controllers/GalleryController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using GDipSA51_Team5.Data;
using GDipSA51_Team5.Models;

namespace GDipSA51_Team5.Controllers
{
    public class GalleryController : Controller
    {
        private readonly Team5_Db db;

        public GalleryController(Team5_Db db)
        {
            this.db = db;
        }

        public IActionResult Index(string searchString)
        {
            string sessionId = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionId;

            Session session = db.Sessions.FirstOrDefault(x => x.Id == sessionId);
            if (session != null)
            {
                ViewData["Username"] = db.Users.FirstOrDefault(x => x.UserId == session.UserId).Username;
            }
            else
            {
                ViewData["Username"] = "Guest";
            }

            ViewData["Products"] = db.Products.Where(s => (s.Name.Contains(searchString) || s.Description.Contains(searchString)) || searchString == null).ToList();

            return View();
        }
    }
}

GDipSA51_Team5/Controllers/IdentityControllers/LogoutController.cs
using Microsoft.AspNetCore.Mvc;
using GDipSA51_Team5.Data;
using GDipSA51_Team5.Models;

namespace GDipSA51_Team5.Controllers
{
    public class LogoutController : Controller
    {
        private readonly Team5_Db db;

        public LogoutController(Team5_Db db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            string sessionId = HttpContext.Request.Cookies["sessionId"];
            db.Sessions.Remove(new Session()
            {
                Id = sessionId
            });

            // ask browser to remove the user's sessionId
            // the next time the browser will not send us any
            // sessionId for this user
            HttpContext.Response.Cookies.Delete("sessionId");

            // direct user back to our default gallery
            return RedirectToAction("Index", "Gallery");
        }
    }
}

GDipSA51_Team5/Controllers/IdentityControllers/RegistrateController.cs
using System.Linq;
using GDipSA51_Team5.Models;
using Microsoft.AspNetCore.Mvc;
using GDipSA51_Team5.Data;

namespace GDipSA51_Team5.Controllers
{
    public class RegistrateController : Controller
    {
        private readonly Team5_Db db;

        public RegistrateController(Team5_Db db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Authenticate(string username, string NewPWD, string ConfirmedPWD)
        {
            User user = db.Users.FirstOrDefault(x => x.Username == username);
            if (user == null)
            {
                if (NewPWD == ConfirmedPWD)
                {
                    User users = new User()
                    {
                        Username = username,
                        Password = NewPWD,
                    };
                    db.Add(users);
                    db.SaveChanges();
                    return RedirectToAction("Login", "Login");
                }
                else
                {
                    ViewData["errMsg"] = "Please enter a consistent password";
                    return View("Index");
                }
            }
            else
            {
                ViewData["errMsg"] = "user has existed";
                return View("Index");
            }

           
        }
    }
    
}

GDipSA51_Team5/Controllers/PurchaseController.cs
using System.Collections.Generic;
using System.Linq;
using GDipSA51_Team5.Models;
using Microsoft.AspNetCore.Mvc;
using GDipSA51_Team5.Data;

namespace GDipSA51_Team5.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly Team5_Db db;

        public PurchaseController(Team5_Db db)
        {
            this.db = db;
        }

        [HttpPost] //when the cart is submitted for purchase
        public IActionResult Transaction()
        {
            Session session = db.Sessions.FirstOrDefault(x => x.Id == HttpContext.Request.Cookies["sessionId"]);

            if (session == null)//if not login, redirect to login page
            {
                return RedirectToAction("Login", "Login");
            }

            int userid = session.UserId;

            List<Cart> carts = db.Carts.Where(x => x.UserId == userid).ToList();

            foreach (Cart item in carts) //for each item in the carts
            {
                ActivationC.AddActivationCode(item, db); //call a method to generate the activationcode and update to the orderdetail database (please refer to the ActivationC class)
                db.Carts.Remove(item);//remove the item from the Carts database
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Index()//When accessing purchase history
        {
            Session session = db.Sessions.FirstOrDefault(x => x.Id == HttpContext.Request.Cookies["sessionId"]);
            if (session == null)//if not login, redirect to login page
            {
                return RedirectToAction("Login", "Login");
            }
            int userid = session.UserId;

            List<Product> product = db.Products.ToList();

            List<OrderDetail> productDetails = db.OrderDetails.Where(x => x.UserId == userid).ToList();

            ViewData["purchaseinfo"] = productDetails;
            ViewData["sessionId"] = Request.Cookies["sessionId"];

            return View();
        }
    }
}

GDipSA51_Team5/Views/Gallery/Index.cshtml
@{
    List<Product> Products = (List<Product>)ViewData["Products"];
}

@section Scripts
{
    <script src="~/js/Add.js"></script>
}

<header>
    <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <a class="navbar-brand" asp-controller="Gallery" asp-action="Index">> hq_pkgs</a>
        <div class="navbar-collapse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark emphasize">Hi, @ViewData["Username"]</a>
                </li>
                @if (ViewData["sessionId"] == null)
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Login" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Registrate" asp-action="Index">Sign Up</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Purchase" asp-action="Index">My Purchases</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Logout" asp-action="Index">Logout</a>
                    </li>
                }
            </ul>
        </div>
        <span style="float:right">
            <a href="/Cart/Cart"><img src="~/img/cart.png" style="height:25px"></a>
            <span id="cartNumber" class="badge" size="1"></span>
        </span>
    </nav>
</header>


<div>
    @using (Html.BeginForm("Index", "Gallery", FormMethod.Get))
    {
        <input type="text" class="form-control-from" name="searchString" style="width: 20%; display:inline; margin-left: calc(2% + 1%)">
        <input type="submit" class="button" style="display:inline;" value="Search">
    }
</div>

<table id="mainframe">
    @for (int i = 0; i < Products.Count; i += 3)
    {
        int j;

        <tr>
            @for (j = 0; j < 3 && i + j < Products.Count; j++)
            {
                <td class="listing">
                    <img class="image" src=@Products[i + j].Url />
                    <div id="pdt-name">@Products[i + j].Name</div>
                    <div id="pdt-descr">@Products[i + j].Description</div>
                    <input type="button" class="button add_button" photo_id=@Products[i + j].ProductId value="$@Products[i + j].Price - Add To Cart">
                </td>
            }

            @for (; j < 3; j++)
            {
                <td class="td-filler"></td>
            }
        </tr>
    }
</table>